### ISSUE TITLE
Unknown error when changing music tracks

### ISSUE THREAD

**Issue by thoralmighty** [SandwichFox/MBCord#44] opened 2023-01-04 12:34 UTC
The following unhandled promise rejection message appears a few times in a row each time the track changes:

```
Error: Unknown Error
    at RPCClient._onRpcMessage (/opt/appimages/mbcord/resources/app.asar/node_modules/discord-rpc/src/client.js:178:19)
    at IPCTransport.emit (node:events:513:28)
    at /opt/appimages/mbcord/resources/app.asar/node_modules/discord-rpc/src/transports/ipc.js:138:18
    at decode (/opt/appimages/mbcord/resources/app.asar/node_modules/discord-rpc/src/transports/ipc.js:92:5)
    at Socket.<anonymous> (/opt/appimages/mbcord/resources/app.asar/node_modules/discord-rpc/src/transports/ipc.js:120:7)
    at Socket.emit (node:events:513:28)
    at emitReadable_ (node:internal/streams/readable:578:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

I'm playing a music album with custom primary art, replacing the auto-generated image Jellyfin provides. I have noticed the cover art is also appearing as a broken image graphic but that occurs even on other albums without manually added art (and without the above error), so might not be related to the issue.

---

DEBUG INFO:
Development Mode: false
Platform: linux (Version 6.1.2-arch1-1)
Architecture: x64
MBCord version: 3.0.6
Node version: 16.17.1
Electron version: 22.0.0
Chrome version: 108.0.5359

**Comment by SandwichFox** [comment] 2023-01-12 08:19
Do you use your Instance on an local ip or an public one? If it is an local ip the pictures wont work. A fix for that is already in the works. But i dont know why you are getting an error when changing tracks.

**Comment by SoftwareRat** [comment] 2023-01-14 21:55
This error message suggests that there is an unknown error occurring in the `discord-rpc` library when it is trying to handle an RPC message.

I can try to reproduce this error and then I can say more

**Comment by manuel-rw** [comment] 2023-01-31 18:33
I have the same error. Using a local IP in my case.

**Comment by SandwichFox** [comment] 2023-03-17 23:18
> I have the same error. Using a local IP in my case.

Discord wont load images with a local ip, but i know that issue already and im searching for a fix in the Near future

**Comment by SandwichFox** [comment] 2023-03-20 14:33
I will close this issue, because i have made this feature disabled by default. If you still want to try this you can enable it

**Closed as completed by SandwichFox** 2023-03-20 14:33 UTC
Labels: bug, linux

**Comment by pogmommy** [comment] 2023-05-18 20:54
Tried to collect as much information as I could when I experienced this issue earlier.

### Generated Report:

```
Error: Unknown Error
    at RPCClient._onRpcMessage (/Applications/mbcord.app/Contents/Resources/app.asar/node_modules/discord-rpc/src/client.js:178:19)
    at IPCTransport.emit (node:events:513:28)
    at /Applications/mbcord.app/Contents/Resources/app.asar/node_modules/discord-rpc/src/transports/ipc.js:138:18
    at decode (/Applications/mbcord.app/Contents/Resources/app.asar/node_modules/discord-rpc/src/transports/ipc.js:92:5)
    at Socket.<anonymous> (/Applications/mbcord.app/Contents/Resources/app.asar/node_modules/discord-rpc/src/transports/ipc.js:120:7)
    at Socket.emit (node:events:513:28)
    at emitReadable_ (node:internal/streams/readable:590:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)
```

---

DEBUG INFO:
Development Mode: false
Platform: darwin (Version 22.4.0)
Architecture: x64
MBCord version: 3.0.7
Node version: 18.12.1
Electron version: 23.1.3
Chrome version: 110.0.5481

### Configuration:

Run at Startup: True
Display as Status: True
Use Time Elapsed: True 
Use Dynamic Images (BETA): True

My Jellyfin server is publicly available, running behind an nginx reverse proxy.

### Error Details:

I'm experiencing the same error message on my M1 MacBook Air running macOS 13.3.1. At times the issue appears to vanish, but when it's present, it seems to occur with every song change. I've had one instance where the same error message presented itself multiple (i think about 4 or 5) times when a song changed.
Despite the error message, MBCord continues to work fine, I have not been able to notice any issues in its communication with my Jellyfin server or with Discord.

### Proposed workaround:

I am unsure how the error message is handled on Linux, but on macOS it appears as a dialogue box that takes up a large portion of the screen and takes focus from other open programs. While not a solution to the error, might it be possible for now to add a setting to suppress these error messages?
